alias c='clear'
alias ls='ls -a --color=auto'
alias lsf='ls -f --color=auto'
alias lsd='ls -d --color=auto'
alias storage='df -h'

alias e='nvim'
alias e-config='e ~/.config/nvim/init.vim'

alias hx-config='hx ~/.config/helix/config.toml'
alias hx-lang='hx ~/.config/helix/languages.toml'

alias tmux-config='e ~/.config/tmux/.tmux.conf'
alias tmux-reload='tmux source ~/.tmux.conf'
alias tl='tmux ls'
alias tk='tmux kill-server'
alias tn='tmux new -s'
alias ta='tmux attach -t'

alias bash-config='e ~/.zshrc'
alias bash-profile='e ~/.zprofile'
alias bash-alias='e ~/.config/aliases/.bash_aliases'
alias bash-reload='source ~/.zshrc && source ~/.zprofile'

alias term-config='e ~/.config/alacritty/alacritty.yml'

alias gs='git status'
alias gb='git branch'
alias gaa='git add -A'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gps='git push'
alias gpl='git pull'
alias gm='git merge'
alias gf='git fetch'

alias sites='cd ~/work/sites'

alias vite-init='npm create vite@latest'

alias craft-ma='php craft migrate/all'
alias craft-pca='php craft project-config/apply'
alias craft-pcr='php craft project-config/rebuild'
alias craft-sk='php craft setup/security-key'
alias craft-sync='craft-ma && craft-pca'
alias craft-ua='craft update all'

alias es='elasticsearch'
alias gat-cd='gatsby clean && gatsby develop'
alias glp='gulp refresh && gulp watch'
alias pamfs='php artisan migrate:fresh --seed'
alias serve='php -S 127.0.0.1:8000'

alias c1='composer self-update --1'
alias c2='composer self-update --2'
alias pecl-73='/usr/local/opt/php@7.3/bin/pecl'
alias pecl-80='/usr/local/opt/php@8.0/bin/pecl'
