alias c='clear'
alias ls='ls -a --color=auto'
alias lsf='ls -f --color=auto'
alias lsd='ls -d --color=auto'
alias storage='df -h'

alias e='nvim'
alias e-config='e ~/.config/nvim/init.vim'

alias tmux-config='e ~/.config/tmux/.tmux.conf'
alias tmux-reload='tmux source ~/.tmux.conf'
alias tl='tmux ls'
alias tk='tmux kill-server'
alias tn='tmux new -s'
alias ta='tmux attach -t'

alias bash-config='e ~/.bashrc'
alias bash-profile='e ~/.profile'
alias bash-alias='e ~/.config/aliases/.bash_aliases'
alias bash-reload='source ~/.bashrc && source ~/.profile'

alias term-config='e ~/.config/alacritty/alacritty.yml'

alias gs='git status'
alias gb='git branch'
alias gaa='git add -A'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gps='git push'
alias gpl='git pull'
alias gm='git merge'
alias gf='git fetch'

alias vite-init='npm create vite@latest'
