alias c='clear'
alias ls='ls -a --color=auto'
alias lsf='ls -f --color=auto'
alias lsd='ls -d --color=auto'
alias storage='df -h'

alias e='vim'
alias e-config='e ~/.vim/vimrc'

alias tmux-config='e ~/.tmux.conf'
alias tmux-reload='tmux source ~/.tmux.conf'
alias tl='tmux ls'
alias tk='tmux kill-server'
alias tn='tmux new -s'
alias ta='tmux attach -t'

alias bash-config='e ~/.bashrc'
alias bash-profile='e ~/.profile'
alias bash-alias='e ~/.bash_aliases'
alias bash-reload='source ~/.bashrc && source ~/.profile'

alias gs='git status'
alias gb='git branch'
alias gaa='git add -A'
alias ga='git add'
alias gc='git commit -m'
alias gco='git checkout'
alias gps='git push'
alias gpl='git pull'
